//
//  LoginModels.swift
//  SantanderSample
//
//  Created by Virgilius Santos on 26/10/18.
//  Copyright (c) 2018 Virgilius Santos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Login{
    
    struct Request: APIRequestLogin {
        typealias Response = Login.Response
        
        var user: String?
        var password: String?
    }
    
    struct LoginSave {
        var user: String?
        var password: String?
    }
    
    struct Response: Codable {
        
        struct Error: Codable {
            var code: Int?
            var message: String?
        }
        
        var userAccount: Login.UserAccount?
        var error: Error?
    }
    
    enum Error: Swift.Error {
        
        case id
        case password
    }
    
    struct UserAccount: Codable {
        var userId: Int?
        var name: String?
        var bankAccount: String?
        var agency: String?
        var balance: Double?
    }
    
    struct ErrorViewModel {
        var error: String?
    }
    
    struct LastUserViewModel {
        var password: String?
        var user: String?
    }
    
}
