//
//  LoginRouter.swift
//  SantanderSample
//
//  Created by Virgilius Santos on 26/10/18.
//  Copyright (c) 2018 Virgilius Santos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol LoginRoutingLogic
{
    func routeToDetails()
}

final class LoginRouter: NSObject
{
    weak var viewController: LoginViewController?
    weak var dataStore: LoginDataStore?
    weak var worker: LoginWorker?

    // MARK: Navigation
  
    func navigateToDetails(source: LoginViewController?, destination: UIViewController)
    {
        DispatchQueue.main.async {
            source?.present(destination, animated: true, completion: nil)
        }
    }
}

extension LoginRouter: LoginRoutingLogic {
    
    // MARK: Routing

    func routeToDetails()
    {
        guard let srv = worker?.serviceManager,
            let user = dataStore?.user else {
            return
        }

        let details = DetailConfigurator(service: srv, user: user).build()
        
        navigateToDetails(source: viewController, destination: details)
    }
}
