# Uncomment the next line to define a global platform for your project
platform :ios, '12.2'
use_frameworks!

def swinject_pods
    pod 'Swinject'
end

target 'SantanderSample' do
    # Pods for SantanderSample
    pod 'IQKeyboardManager'
    pod 'SwiftKeychainWrapper'
end

def testing_pods
    pod 'Quick' 
    pod 'Nimble'
    swinject_pods
end

target 'SantanderSampleTests' do
    testing_pods
end
